export enum ContentType {
    JSON = "application/json",
    HTML = "text/html",
    TEXT = "text/plain",
    FORM_URLENCODED = "application/x-www-form-urlencoded",
    FORM_DATA = "multipart/form-data",
    XML = "application/xml",
    JAVASCRIPT = "application/javascript",
    CSS = "text/css",
    CSV = "text/csv",
    PDF = "application/pdf",
    ZIP = "application/zip",
    OCTET_STREAM = "application/octet-stream",
    PNG = "image/png",
    JPEG = "image/jpeg",
    GIF = "image/gif",
    SVG = "image/svg+xml",
    WEBP = "image/webp",
    MP4 = "video/mp4",
    MP3 = "audio/mpeg",
    WAV = "audio/wav",
    ICO = "image/vnd.microsoft.icon",
    AVIF = "image/avif",
    BMP = "image/bmp"
}
